### PR TITLE
Fix HTTP 207 didn't handled properly

### PR DESCRIPTION
**Pull request by kotori2**
My environment: `nginx/1.18.0 (Ubuntu)`, `sardine-android:0.8`
On Nginx WebDAV server, if you send a `PROPFIND` request, it will return a HTTP 207 response listing all possible files. But in my case, `sardine.exists` checks only the HTTP status code <= 299 instead of parsing into the XML file.
image
Since I don't want to implement a XML parser, I change this request to `HEAD` as [the OG sardine did](https://github.com/lookfirst/sardine/blob/df3d477ecb57529a0741647e8132ab6fcb2f7700/src/main/java/com/github/sardine/impl/SardineImpl.java#L1004).

### CODE REVIEW

**Comment by guillaume-tgl** [comment]
I've just fixed some tests in master. Could you merge master into your branch to make sure tests are still passing?

**Comment by kotori2** [comment]
> Workflow runs completed with no jobs

GHA not configured for PR?

**Comment by guillaume-tgl** [comment]
I've added a condition to trigger on PRs. Could you merge master again?

**Comment by kotori2** [comment]
> All checks have passed

**Review by guillaume-tgl — APPROVED** [review]

**Comment by dayanmasiha-hub** [comment]
> My environment: `nginx/1.18.0 (Ubuntu)`, `sardine-android:0.8`
> On Nginx WebDAV server, if you send a `PROPFIND` request, it will return a HTTP 207 response listing all possible files. But in my case, `sardine.exists` checks only the HTTP status code <= 299 instead of parsing into the XML file.
> image
> Since I don't want to implement a XML parser, I change this request to `HEAD` as [the OG sardine did](https://github.com/lookfirst/sardine/blob/df3d477ecb57529a0741647e8132ab6fcb2f7700/src/main/java/com/github/sardine/impl/SardineImpl.java#L1004).

**Pull request merged**
