### PR TITLE
Add support for InputStream in PUT method

### PR DESCRIPTION
**Pull request by guillaume-tgl**

### CODE REVIEW

**Review by bvirlet — APPROVED** [review]

**Review by 3c71 — CHANGES_REQUESTED** [review]
From my various tests sending files using InputStream, OkHttp never re-opens the stream so using a 'provider' is pretty useless. The writeTo() method will using the given stream and send the whole content, be it a few Kb or several Gb. Tested on a NAS with up-to 40GB files.

**Comment by guillaume-tgl** [comment]
This OkHttp issue says the opposite: https://github.com/square/okhttp/issues/3585

**Comment by 3c71** [comment]
I don't see any valid use-case in this issue. Only an 'occasionally'. Original Sardine library for Java is also using an InputStream, so I'm not sure there's a rational to divert from that so much that building apps for Android and others will no longer be compatible.

**Comment by 3c71** [comment]
That doesn't prevent the Android version from providing a put() method with InputStream and another for InputStreamProvider, though I don't see any use for the later.

InputStream is supposedly used for large content, so sending it multiple times seems unreasonable.

**Review by Mrfiziee — APPROVED** [review]

**Pull request closed without merging**
